### ISSUE TITLE
Mismatch with content in paper?

### ISSUE THREAD

**Issue by cgueret** [yuyanislearning/CTRL-PG#1]
This line of code:
https://github.com/yuyanislearning/CTRL-PG/blob/9c3c9fe7f4d47dcf18550b270d8f4efe2ba84e90/sources/model_layers.py#L38

Does not seem to align with the loss as defined in the paper in Figure 2 where a min and a max are used

**Comment by yuyanislearning** [comment]
Thanks for pointing out, it should be max and max, the figure in the paper will be changed accordingly in the final version.
