### ISSUE TITLE
Some questions about code

### ISSUE THREAD

**Issue by Peng-KG** [yuyanislearning/CTRL-PG#2]
Hi, your work is excellent and l'm interested in your work.However,l run the code as following:
python run_relation_extraction.py --do_train      --do_eval      --tbd      --evaluate_during_training      --do_lower_case      --data_dir ../tbd/all_context/      --max_seq_length 128      --per_gpu_eval_batch_size=8      --per_gpu_train_batch_size=8      --learning_rate 2e-5      --num_train_epochs 10.0      --output_dir ../tbd      --overwrite_output_dir      --data_aug triple_rules      --aug_round 0      --psllda 0.5
and the final results are as following:
03/30/2021 08:09:36 - INFO - __main__ -     macro-f1 = 0.177363026778508
03/30/2021 08:09:36 - INFO - __main__ -     macro-precision = 0.21496009994047868
03/30/2021 08:09:36 - INFO - __main__ -     macro-recall = 0.20795683333271806
03/30/2021 08:09:36 - INFO - __main__ -     micro-f1 = 0.35315985130111527
03/30/2021 08:09:36 - INFO - __main__ -     micro-precision = 0.35315985130111527
03/30/2021 08:09:36 - INFO - __main__ -     micro-recall = 0.35315985130111527

it is lower than the paper results.Maybe some wrong with me way, could you help me?

**Comment by yuyanislearning** [comment]
Hi, 
Thanks for pointing out, the issue has been fixed. Remember to delete the cache file to load the data again.
